### ISSUE TITLE
Add Form A functionality

### ISSUE THREAD

**Issue by ryanjagar** [icefoganalytics/signing-authority#22]
### Backend API
**Methods**
- [x] POST (create)
- [x] GET (one)
- [x] GET (byDepartment)
- [x] POST(search)
- [x] PUT (update)
- [x] POST (upload) 

**Other**
- [x] Secure with JWT
- [ ] Audit (create, edit, cancelled)
- [ ] Print form
 
### Front End
- [x] Nav
- [x] Form display
- [x] Create Button/Page
- [ ] Upload modal
- [ ] Show signed form

**Comment by ryanjagar** [comment]
@jocosityjessica would you provide a copy of a FORM A that we can model from?

**Comment by jocosityjessica** [comment]
Attached with one caveat - the "departmental use" column headings will be changed to reflect the actual use of these columns across departments. 
The good news is that the Form A will not require validation tie ins for coding. The bu
[Signing Authorities Form A - Delegation Chart.docx](https://github.com/icefoganalytics/signing-authority/files/8855669/Signing.Authorities.Form.A.-.Delegation.Chart.docx)
siness will provide rules to departments to ensure the lines are split up in the way we're expecting, but we are not planning to enforce "code only" lines like we are for the Form Bs

**Comment by jocosityjessica** [comment]
hey @ryanjagar the PDF of a Form A is attached here so you can see the formatting
[Signing Authorities Form A - Delegation Chart.pdf](https://github.com/icefoganalytics/signing-authority/files/8857066/Signing.Authorities.Form.A.-.Delegation.Chart.pdf)

**Comment by ryanjagar** [comment]
@jocosityjessica what is the key for Form A's?  Whereas Form B's are keyed to a person - regardless of their department.  Form A's seem to be organized around a position name.  What makes it more interesting is that I believe Form A's can cover have multiple positions in identified within a single Form A.  Further, I believe the same position name can have different Form A authorities even within the same department - let alone across departments.  

So, as an internal auditor searching for a FORM A for a finance admin in ICT -  how do I find what I'm looking for?

**Comment by jocosityjessica** [comment]
The only further formatting / layout update for the FORM A is to remove the Departmental Use columns. We have comptroller approval for this change X-D
