### ISSUE TITLE
Form B statuses

### ISSUE THREAD

**Issue by ryanjagar** [icefoganalytics/signing-authority#23]
A FORM B are cancelled for a variety of reasons.  The reasons need to be identified by the product owner and added to the system.

**Comment by jocosityjessica** [comment]
@ryanjagar on my to-do list this week is to produce a FutureState delete/archive workflow and run it by the business for approval. I think that should be a separate issue/task.

The statuses in this ticket, to me, would pertain more to the status as the Form B is drafted and circulated for approval.
