### ISSUE TITLE
Source departments

### ISSUE THREAD

**Issue by ryanjagar** [icefoganalytics/signing-authority#28]
Implement a strategy to manage the list departments for employees.  This might be a local cached copy or an API call.  
_Departments are tightly coupled with account codes_. It may be worth spending to find (or build) an authoritative source of department and department code information.

**Comment by ryanjagar** [comment]
This question of whether or not the SAA app becomes the authoritative source for departments and department codes is one for the business owner.

**Comment by datajohnson** [comment]
My vote goes to FM being the authoritative source. It's easy enough to pull the department list from data warehouse API.

**Comment by ryanjagar** [comment]
I like it! 

@datajohnson would you find/build that endpoint? I'll update the [API documentation](https://app.swaggerhub.com/apis/GOY/yg-finance-api/1.1.1) when it's done. 

@jocosityjessica would you confirm with the product owner that sourcing department and their account mask from FE (the data warehouse specifically) is acceptable?

**Comment by jocosityjessica** [comment]
I lean on @datajohnson 's opinion on the most appropriate authoritative source. The product owner is primarily concerned about the App (and, subsequently, the Online Marketplace) being kept as up to date with Infor / FM. We talked about whether that would hop through Quest or Front End or any other system I haven't actually seen with my own two eyes.
There's a call on June 8 @ 1pm to finally-finalize this information. MJ is on it, as is Gritt and the Online Marketplace vendor. Let me know if you'd be keen to sit in, Ryan.

For another task/to-do perhaps, is confirming where the Signing Auth App pulls codes for validation. I'm assuming it will also be FM, but if not, am curious how that will work.
